import { esc } from './operations-view.js?v=0.5.1-mach';
import { pendingChanges, activePeople } from './oneq-changes.js';
export const stateLabels={preparing:'전달 준비',received:'수신 확인',pending:'반영 대기',applied:'반영 완료',cancelled:'취소',conflict:'최신본 확인 필요',unknown:'반영 여부 확인 필요'};
const button=(action,text)=>`<button class="button secondary" data-mach="${action}">${text}</button>`;
const describe=p=>p?`${p.name} · ${p.organization} · ${p.position} · ${{attending:'참석',absent:'불참',replaced:'대리로 교체'}[p.status]}`:'등록 전';
export function changesView(s, comparison=null, incoming=null) {
 const changes=[...new Map([...pendingChanges(s,'nameplate'),...pendingChanges(s,'prime')].map(c=>[c.id,c])).values()];
 return `<section id="mach-changes" class="panel no-print"><h2>변경사항 확인</h2><p>참석 ${activePeople(s).length}명 · 이력 포함 ${s.attendees.length}명. 선택한 변경은 연결한 도구에서 다시 확인한 뒤 반영합니다.</p><p class="small">같은 PC·브라우저에서 연결 버튼으로 연 창 사이에 전달합니다. 다른 PC에서는 연동 JSON을 이용하세요. 좌석·디자인은 각 도구에서 보관합니다.</p><div class="row gap">${button('select-all','전체 선택')}${button('send-prime','선택한 변경을 좌석배치기로 보내기')}${button('send-nameplate','선택한 변경을 명패로 보내기')}${button('export','선택한 변경 JSON 저장')}${button('import','연동 결과 JSON 가져오기')}${button('undo','마지막 적용 전 복원')}${button('summary','변경 요약 복사')}</div><input type="file" id="mach-file" accept=".json" hidden><div class="mach-status" role="status">${['prime','nameplate'].map(t=>`<p><strong>${t==='prime'?'PRIME 좌석':'명패'}</strong>: ${s.mach.targets[t]?.rosterReceipt ? `명단 ${stateLabels[s.mach.targets[t]?.status] || '상대 도구 확인'} · 출력 상태 수신 확인` : stateLabels[s.mach.targets[t]?.status] || '전달 전'} ${s.mach.targets[t]?.transferId?button(`retry-${t}`,'같은 보낸 내용 확인'):''}</p>`).join('')}</div>${changes.length?`<ul class="record-list">${changes.map(c=>`<li class="record-card"><label><input type="checkbox" data-mach-select="${esc(c.id)}" checked> <strong>${esc(c.after.name)||'이름 미입력'} · ${c.type}</strong></label><p>${esc(describe(c.before))} → ${esc(describe(c.after))}</p><p class="small">좌석: ${pendingChanges(s,'prime').some(x=>x.id===c.id)?'반영 대기':'상대 도구 확인'} · 명패: ${pendingChanges(s,'nameplate').some(x=>x.id===c.id)?'반영 대기':'상대 도구 확인'}</p><p>현재 좌석: ${esc(c.seat)} · ${c.impact}</p><p class="small">영향: 명패·좌석배치표·운영명단 / 주차·다과·촬영·준비물 인원 재확인</p></li>`).join('')}</ul>`:'<p>도구에 전달할 참석자 변경이 없습니다.</p>'}${comparison?comparisonView(s,comparison):''}${incoming?`<section class="note"><h3>도구 결과 반영 확인</h3><p>${esc(incoming.payload.eventName || '행사')} · ${incoming.payload.kind==='seats'?'좌석 결과':'출력·회수 확인 결과'}</p><p>참석자 기본정보는 유지하며 선택한 도구의 확인 상태만 저장합니다.</p>${(incoming.payload.participants||incoming.payload.records||[]).map(r=>`<p>${esc(s.attendees.find(p=>p.id===r.participantId)?.name||r.participantId)}: ${esc(r.seatId || ({printed:'출력 확인',recall:'기존 명패 회수 필요',recalled:'회수 확인',unknown:'출력 여부 미확인',changed:'수정 재출력 필요',new:'신규 출력 필요'}[r.status]) || '미배정')}</p>`).join('')}<div class="row">${button('feedback-apply','결과 확인 후 반영')}${button('feedback-cancel','취소')}</div></section>`:''}<p class="small">이미 내려받은 PDF·종이는 자동으로 바뀌지 않습니다. 실제 출력 확인과 회수 여부는 명패 도구에서 확인하세요.</p>${feedbackView(s)}</section>`;
}
function comparisonView(s,comparison) {return `<section class="import-preview"><h3>수정명단 비교 · 선택한 행만 반영</h3><p>이름이 같아도 자동 병합하지 않습니다. 기존 참석자 정정 또는 새 참석자를 직접 선택하세요. 빠진 참석자는 유지됩니다.</p>${comparison.map(({row,candidates},i)=>`<div class="record-card"><p>${esc(row.name)} · ${esc(row.org)} · ${esc(row.title)}</p><label>반영 대상 <select data-mach-match="${i}"><option value="">반영하지 않음 · 확인 필요</option><option value="new">새 참석자로 추가</option>${s.attendees.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.org)} · ${esc(p.title)}${candidates.includes(p.id)?' (이름 일치 후보)':''}</option>`).join('')}</select></label></div>`).join('')}<div class="row">${button('compare-apply','선택한 수정명단 반영')}${button('compare-cancel','비교 취소')}</div></section>`;}
export function attendanceControls(r){return `<div class="row gap"><label>참석 상태 <select data-mach-attendance="${esc(r.id)}">${[['attending','참석'],['absent','불참'],['replaced','대리로 교체']].map(([v,l])=>`<option value="${v}" ${(r.attendance||'attending')===v?'selected':''} ${v==='replaced'?'disabled':''}>${l}</option>`).join('')}</select></label><button class="button secondary" data-mach="delegate" data-person="${esc(r.id)}">대리참석자 등록</button></div>${r.replaces?'<p class="small">대리참석 관계를 유지합니다. 자리 승계는 좌석 도구에서 별도로 확인하세요.</p>':''}`;}
export function feedbackView(s){
 const records=s.mach?.feedback?.nameplate?.records||[],seats=s.mach?.feedback?.prime?.seats||[];
 const stages=['prime','nameplate'].map(t=>`<p>${t==='prime'?'좌석배치':'명패'}: ${s.mach?.targets?.[t]?.rosterReceipt ? `명단 ${stateLabels[s.mach.targets[t].status]} · 출력 상태 수신 확인` : stateLabels[s.mach?.targets?.[t]?.status] || (s.mach?.feedback?.[t] ? '도구 결과 확인' : '전달 전')}</p>`).join('');
 return `<section class="panel"><h3>연결 도구 확인 상태</h3>${stages}${seats.length?`<details><summary>확인한 현재 좌석</summary>${seats.map(r=>`<p>${esc(s.attendees.find(p=>p.id===r.participantId)?.name||'참석자')}: ${esc(r.seatId||'미배정')}${r.seatLocked?' · 고정석':''}</p>`).join('')}</details>`:''}${records.length?`<div><h3>출력물 교체 확인</h3>${records.map(r=>`<p>${esc(s.attendees.find(p=>p.id===r.participantId)?.name||'참석자')}: ${esc({printed:'출력 확인',recall:'기존 명패 회수 필요',recalled:'회수 확인',unknown:'출력 여부 미확인',changed:'수정 재출력 필요',new:'신규 출력 필요'}[r.status]||r.status)}</p>`).join('')}</div>`:''}</section>`;
}
