// 확인한 운영 정보만 등록하세요. null은 미등록 상태입니다.
export const STORAGE_KEY = "erica-event-oneq:prototype:v0.1";
export const STEPS = [
  "장소",
  "행사 정보",
  "먼저 요청할 일",
  "식순·양식",
  "좌석·명패",
  "화면·안내물",
  "준비표",
];
export const VENUES = [
  {
    id: "prime",
    name: "프라임 컨퍼런스홀",
    note: "프라임 전용 좌석배치 도구 연결",
    symbol: "01",
    rental: { department: null, contact: null, url: null, conditions: null },
  },
  {
    id: "history",
    name: "히스토리라운지",
    note: "장소 확보 여부부터 확인해 주세요",
    symbol: "02",
    rental: { department: null, contact: null, url: null, conditions: null },
  },
  {
    id: "department",
    name: "부서 자체 장소",
    note: "부서에서 사용하는 회의실·행사 공간",
    symbol: "03",
    rental: null,
  },
  {
    id: "other",
    name: "기타 장소",
    note: "사용하실 장소를 직접 적어 주세요",
    symbol: "04",
    rental: { department: null, contact: null, url: null, conditions: null },
  },
  {
    id: "unknown",
    name: "아직 미정",
    note: "장소가 정해지지 않아도 괜찮아요",
    symbol: "…",
    rental: null,
  },
];
export const LINKS = {
  mach: { name: "PROJECT MACH", url: "https://erakeun.github.io/ERICAAI/" },
  seat: {
    name: "프라임 좌석배치",
    url: "https://erakeun.github.io/erica-seat-planner/",
  },
  nameplate: {
    name: "명패 제작기",
    url: "https://erakeun.github.io/nameplate-maker/",
  },
  welcome: {
    name: "웰컴보드 제작기",
    url: "https://erakeun.github.io/welcome-board-maker/",
  },
  signage: {
    name: "디지털 사이니지 제작기",
    url: "https://erakeun.github.io/digital-signage-maker/",
  },
  notice: {
    name: "안내문 제작기",
    url: "https://erakeun.github.io/notice-maker/",
  },
  led: {
    name: "컨퍼런스홀 LED 제작기",
    url: "https://erakeun.github.io/conference-hall-led-maker/",
  },
  pr: {
    name: "보도자료 기초자료 제출",
    url: "https://erakeun.github.io/erica-pr-request/",
  },
  press: {
    name: "촬영·취재 협조 요청",
    url: "https://erakeun.github.io/erica-press/",
  },
};
const seq = (id, title, what, role, check, script) => ({
  id,
  title,
  what,
  role,
  check,
  script,
});
export const EVENTS = [
  {
    id: "mou",
    name: "협약식(MOU)",
    short: "협약식",
    description: "협약서 서명과 교환을 함께 준비해요",
    supplies: [
      "최종 협약서와 서명 위치",
      "서명용 펜·서류 받침",
      "협약서 교환 동선",
    ],
    agenda: [
      seq(
        "open",
        "개회",
        "행사의 시작과 목적을 안내합니다.",
        "사회자",
        "행사명·음향·시작 신호 확인",
        "지금부터 협약식을 시작하겠습니다.",
      ),
      seq(
        "introduce",
        "참석자 소개",
        "참석자를 사전 합의한 순서로 소개합니다.",
        "사회자",
        "호칭과 소개 순서 사전 확인",
        "오늘 함께해 주신 참석자를 소개하겠습니다.",
      ),
      seq(
        "remarks",
        "양측 인사말",
        "양측의 인사말을 듣습니다.",
        "사전에 지정한 대표",
        "발언자·발언 순서·마이크 확인",
        "이어서 사전에 정한 순서에 따라 인사 말씀을 듣겠습니다.",
      ),
      seq(
        "sign",
        "협약서 서명",
        "최종 확인된 협약서에 서명합니다.",
        "확인된 서명자·서류 배치 담당",
        "서명자 확인 / 최종 협약서와 서명 위치 확인 / 펜 준비 / 서류 배치 담당 확인",
        "다음은 협약서 서명 순서입니다. 서명자께서는 준비된 자리로 이동해 주시기 바랍니다.",
      ),
      seq(
        "exchange",
        "교환·기념촬영",
        "협약서를 교환하고 사진을 촬영합니다.",
        "진행 담당·촬영 담당",
        "교환 방법·촬영 위치·서류 방향 확인",
        "협약서를 교환한 뒤 기념촬영을 진행하겠습니다.",
      ),
      seq(
        "close",
        "폐회",
        "마무리와 이동 안내를 전합니다.",
        "사회자",
        "후속 일정·퇴장 동선 확인",
        "이상으로 협약식을 마치겠습니다. 함께해 주셔서 감사합니다.",
      ),
    ],
  },
  {
    id: "donation",
    name: "기금전달식",
    short: "기금전달식",
    description: "전달 순서와 감사의 자리를 준비해요",
    supplies: [
      "전달용 물품 또는 보드 사용 여부",
      "전달·촬영 위치와 동선",
      "전달 물품 배치 담당",
    ],
    agenda: [
      seq(
        "open",
        "개회·소개",
        "행사를 열고 참석자를 소개합니다.",
        "사회자",
        "행사명·소개 순서·호칭 확인",
        "지금부터 기금전달식을 시작하겠습니다. 참석해 주신 여러분께 감사드립니다.",
      ),
      seq(
        "purpose",
        "기부 취지 소개",
        "사전에 확인한 기부 취지를 소개합니다.",
        "사회자 또는 지정한 대표",
        "공개 가능한 소개 내용 확인",
        "이번 기부의 취지를 간단히 소개하겠습니다.",
      ),
      seq(
        "handover",
        "전달 순서",
        "사전 협의한 방식으로 전달을 진행합니다.",
        "지정한 전달자·수령자·진행 담당",
        "전달 물품·전달 방향·위치·배치 담당 확인",
        "이어서 전달 순서를 진행하겠습니다. 관계자께서는 안내에 따라 자리해 주시기 바랍니다.",
      ),
      seq(
        "thanks",
        "감사 말씀",
        "감사의 뜻을 전합니다.",
        "사전에 지정한 대표",
        "발언자·순서·마이크 확인",
        "다음으로 감사 말씀을 듣겠습니다.",
      ),
      seq(
        "photo",
        "기념촬영",
        "참석자와 기념사진을 촬영합니다.",
        "촬영 담당·진행 담당",
        "촬영 인원·위치·배경 확인",
        "기념촬영을 진행하겠습니다. 안내에 따라 자리해 주시기 바랍니다.",
      ),
      seq(
        "close",
        "폐회",
        "마무리와 후속 안내를 전합니다.",
        "사회자",
        "물품 회수·퇴장 안내 확인",
        "이상으로 기금전달식을 마치겠습니다. 감사합니다.",
      ),
    ],
  },
  {
    id: "meeting",
    name: "미팅·간담회",
    short: "미팅·간담회",
    description: "안건과 논의, 후속 조치를 정리해요",
    supplies: ["안건 자료", "메모·기록 수단", "자료 공유 방법"],
    agenda: [
      seq(
        "introduce",
        "참석자 소개",
        "참석자와 역할을 소개합니다.",
        "진행 담당",
        "소개 순서·호칭 확인",
        "시작에 앞서 참석자 여러분을 소개하겠습니다.",
      ),
      seq(
        "agenda",
        "안건 안내",
        "오늘 논의할 안건을 안내합니다.",
        "진행 담당·안건 담당",
        "최종 안건·배포 자료 확인",
        "오늘 논의할 안건을 안내드리겠습니다.",
      ),
      seq(
        "discussion",
        "논의",
        "안건별 의견을 나눕니다.",
        "참석자·진행 담당",
        "진행 방식·기록 담당·화면 점검",
        "안건에 대해 의견을 나누겠습니다.",
      ),
      seq(
        "followup",
        "결정사항·후속 조치 정리",
        "결정된 내용과 후속 담당을 확인합니다.",
        "진행 담당·기록 담당",
        "결정 내용·후속 담당·공유 방법 확인",
        "논의한 내용을 정리하고 후속 조치를 확인하겠습니다.",
      ),
      seq(
        "close",
        "종료",
        "회의를 마무리합니다.",
        "진행 담당",
        "자료 회수 여부·정리 확인",
        "이상으로 오늘 논의를 마치겠습니다. 감사합니다.",
      ),
    ],
  },
  {
    id: "award",
    name: "시상식",
    short: "시상식",
    description: "호명, 시상과 촬영 동선을 준비해요",
    supplies: [
      "상장·상패·부상 준비 여부",
      "호명 순서와 수여 물품 대조",
      "수상자 대기·이동 위치",
    ],
    agenda: [
      seq(
        "open",
        "개회",
        "시상식의 시작을 안내합니다.",
        "사회자",
        "행사명·시작 신호 확인",
        "지금부터 시상식을 시작하겠습니다.",
      ),
      seq(
        "guide",
        "시상 안내",
        "시상 내용과 진행 방법을 소개합니다.",
        "사회자",
        "시상 부문·진행 방식 확인",
        "오늘의 시상 내용과 진행 순서를 안내드리겠습니다.",
      ),
      seq(
        "present",
        "수상자 호명·시상",
        "수상자를 호명하고 상을 수여합니다.",
        "사회자·지정한 시상자·물품 담당",
        "호명 순서·상장 대조·물품 배치·이동 동선 확인",
        "호명되신 분께서는 안내에 따라 앞으로 나와 주시기 바랍니다.",
      ),
      seq(
        "photo",
        "기념촬영",
        "시상 후 기념사진을 촬영합니다.",
        "촬영 담당·진행 담당",
        "촬영 위치·단체 촬영 여부 확인",
        "기념촬영을 진행하겠습니다.",
      ),
      seq(
        "close",
        "마무리",
        "축하와 종료 안내를 전합니다.",
        "사회자",
        "퇴장·물품 전달 누락 확인",
        "수상하신 여러분께 축하드립니다. 이상으로 시상식을 마치겠습니다.",
      ),
    ],
  },
  {
    id: "other",
    name: "기타 행사",
    short: "기타 행사",
    description: "기본 흐름을 행사에 맞게 조정해요",
    supplies: ["주요 순서에 필요한 물품", "진행 역할과 현장 동선"],
    agenda: [
      seq(
        "open",
        "개회",
        "행사의 시작과 취지를 안내합니다.",
        "사회자 또는 진행 담당",
        "행사명·안내 사항 확인",
        "지금부터 행사를 시작하겠습니다.",
      ),
      seq(
        "main",
        "주요 순서",
        "행사 목적에 맞는 주요 순서를 진행합니다.",
        "사전에 지정한 담당",
        "세부 순서·역할·물품을 행사에 맞게 조정",
        "이어서 주요 순서를 진행하겠습니다.",
      ),
      seq(
        "close",
        "마무리",
        "행사를 마치고 후속 안내를 전합니다.",
        "진행 담당",
        "후속 안내·퇴장 동선 확인",
        "함께해 주셔서 감사합니다. 이상으로 행사를 마치겠습니다.",
      ),
    ],
  },
];
// 실제 .hwp를 assets/templates/에 넣은 뒤 path를 등록하세요. 없는 파일은 활성화되지 않습니다.
export const TEMPLATES = [
  ...EVENTS.map((e) => ({
    id: `agenda-${e.id}`,
    event: e.id,
    label: `${e.short} 식순지`,
    path: null,
  })),
  { id: "agreement-mou", event: "mou", label: "협약서 예시", path: null },
];
export const OUTPUTS = [
  {
    id: "welcome",
    title: "방문객 환영 화면 만들기",
    description: "행사명과 환영 문구를 담은 화면을 준비해요.",
    delivery: "현장 화면 송출 확인",
  },
  {
    id: "signage",
    title: "안내 화면 만들기",
    description: "행사 안내를 담은 화면을 준비해요.",
    delivery: "현장 화면 송출 확인",
  },
  {
    id: "notice",
    title: "입구·이동 안내문 만들기",
    description: "참석자가 찾아올 수 있도록 안내문을 준비해요.",
    delivery: "인쇄·부착 위치 확인",
  },
  {
    id: "led",
    title: "컨퍼런스홀 LED 화면 만들기",
    description: "설치 장소와 화면 규격을 먼저 확인해 주세요.",
    delivery: "현장 화면 송출 확인",
  },
];
